import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/providers/providers";
import Navbar from "@/components/navbar";

const inter = localFont({
  src: "../../public/fonts/InterVariable.ttf",
  variable: "--font-inter",
  display: "swap",
});

const abcFavorit = localFont({
  src: "../../public/fonts/ABCFavorit-Medium.woff2",
  variable: "--font-abc-favorit",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Privy Next demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${abcFavorit.variable} flex min-h-screen flex-col items-center justify-center p-4 sm:p-24 bg-[#050505]`}
      >
        <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
          {/* Background Blobs for Premium Feel */}
          <div className="fixed left-0 top-0 flex h-full w-full justify-center overflow-hidden pointer-events-none">
            <div className="relative flex w-full h-full max-w-[100vw] items-center justify-center">
              <div className="absolute top-[20%] left-[10%] h-[300px] w-[300px] rounded-full bg-purple-600/20 blur-[100px]" />
              <div className="absolute bottom-[20%] right-[10%] h-[250px] w-[250px] rounded-full bg-cyan-500/20 blur-[100px]" />
            </div>
          </div>
        </div>
        <Providers>
          <>
            <Navbar />
            {children}
          </>
        </Providers>
      </body>
    </html>
  );
}
